apiVersion: v1
kind: Service 

metadata:
  name: nginx-svc

spec:
  type: NodePort
  selector:
    name: nginx-app
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 32000
